In [1]:
from pathlib import Path
import pandas as pd

# Путь к срезу датасета
data_path = Path("../data/interim/source.parquet")

# Загружаем данные
df = pd.read_parquet(data_path)

# Выводим основные сведения
print("Датасет успешно загружен!")
print(f"Количество строк: {df.shape[0]}")
print(f"Количество столбцов: {df.shape[1]}")

display(df.head())

Датасет успешно загружен!
Количество строк: 200000
Количество столбцов: 8

,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,2009-06-15 17:26:21.0000001,4.5,2009-06-15 17:26:21 UTC,-73.844311,40.721319,-73.841610,40.712278,1
1,2010-01-05 16:52:16.0000002,16.9,2010-01-05 16:52:16 UTC,-74.016048,40.711303,-73.979268,40.782004,1
2,2011-08-18 00:35:00.00000049,5.7,2011-08-18 00:35:00 UTC,-73.982738,40.761270,-73.991242,40.750562,2
3,2012-04-21 04:30:42.0000001,7.7,2012-04-21 04:30:42 UTC,-73.987130,40.733143,-73.991567,40.758092,1
4,2010-03-09 07:51:00.000000135,5.3,2010-03-09 07:51:00 UTC,-73.968095,40.768008,-73.956655,40.783762,1

In [2]:
# Типы данных каждого столбца
print("Типы данных:")
display(df.dtypes.to_frame(name="Тип данных"))

# Количество уникальных значений
print("Количество уникальных значений:")
display(df.nunique().to_frame(name="Уникальных значений"))

# Количество и доля пропусков
missing = pd.DataFrame({
    "Пропусков": df.isna().sum(),
    "Доля пропусков, %": (df.isna().mean() * 100).round(2)
})

print("Пропущенные значения:")
display(missing)

# Общая информация о датасете
print("Общая информация:")
df.info()

Типы данных:

                  Тип данных
key                      str
fare_amount          float64
pickup_datetime          str
pickup_longitude     float64
pickup_latitude      float64
dropoff_longitude    float64
dropoff_latitude     float64
passenger_count        int64

Количество уникальных значений:

                   Уникальных значений
key                             200000
fare_amount                       1215
pickup_datetime                 193291
pickup_longitude                 71006
pickup_latitude                  83863
dropoff_longitude                77062
dropoff_latitude                 90608
passenger_count                      7

Пропущенные значения:

                   Пропусков  Доля пропусков, %
key                        0                0.0
fare_amount                0                0.0
pickup_datetime            0                0.0
pickup_longitude           0                0.0
pickup_latitude            0                0.0
dropoff_longitude          1                0.0
dropoff_latitude           1                0.0
passenger_count            0                0.0

Общая информация:
<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   key                200000 non-null  str
 1   fare_amount        200000 non-null  float64
 2   pickup_datetime    200000 non-null  str
 3   pickup_longitude   200000 non-null  float64
 4   pickup_latitude    200000 non-null  float64
 5   dropoff_longitude  199999 non-null  float64
 6   dropoff_latitude   199999 non-null  float64
 7   passenger_count    200000 non-null  int64
dtypes: float64(5), int64(1), str(2)
memory usage: 21.9 MB